language: java
sudo: required
dist: trusty

env:
  global:
    - aptly=35.202.97.139
    
addons:
  apt:
    packages:
      - curl

script:
  - ./gradlew clean packDeb
  - sed -i -- 's/aptly-ip/$aptly/g' upload-deb.sh
  - chmod +x ./upload-deb.sh
  - ./upload-deb.sh
  - sed -i -- 's/$aptly/aptly-ip/g' upload-deb.sh
