language: java
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - curl

script:
  - ./gradlew clean packDeb
  - sed -i -- 's/aptly-ip/35.202.97.139/g' upload-deb.sh
  - chmod +x ./upload-deb.sh
  - ./upload-deb.sh
  - sed -i -- 's/35.202.97.139/aptly-ip/g' upload-deb.sh
