language: java
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - openjdk-8-jdk
jdk: openjdk8
script:
  - ./gradlew clean packDeb
deploy:
  provider: gcs
  access_key_id: "GOOGRUOCTH35Q3OHWK6N"
  secret_access_key: "8UBMdQOESSk9UtNVsXeuX/Wu8fGqqG7p+tXTRtVw"
  bucket: "travis-bucket"
  skip_cleanup: true
